### ISSUE TITLE
Integration with other scRNA datasets

### ISSUE THREAD

**Issue by jindalk** [AllonKleinLab/paper-data#7]
Hi, thanks a lot for making your data available on github. I'm planning to integrate the in vitro data with existing 10x scRNA datasets. Do you have any recommendations on how to go about that, given that the counts provided are already normalized?

Thanks

**Comment by calebweinreb** [comment]
It might be best to use a published approach for batch correction /
combining scSeq datasets.

Typically when I combine datasets, I make sure they are total counts
normalized so that cells in both datasets have the same total counts, and
then we do "PCA-batch correction" which is described in the supp methods of
"Lineage tracing on transcriptional landscapes links state to fate during
differentiation"

**Comment by velten-lab** [comment]
Along the same lines, I like to work with integration methods that start with raw count tables. If I understand you right, the files you provide contain library size normalized values. Could you additionally provide the raw count tables?
Thanks and greetings, Lars

**Comment by calebweinreb** [comment]
The raw counts are not available but you can recover them from the
normalized counts. During normalization each cell was uniformly scaled by
common factor. You can recover this factor by taking the reciprocal of the
smallest non-zero gene-expression value for that cell. You should then be
able to rescale each cell such that all the gene expression values are
integers.
